spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mariadb
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: alsd7856
  jpa:
    open-in-view: true
    generate-ddl: true
    show-sql: true
    hibernate:
     ddl-auto: create-drop
UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data

auth:
  jwtExpirationMs: 600000
  jwtsecret: JWTSuperSecretKey